### ISSUE TITLE
Contributing Documentation

### ISSUE THREAD

**Issue by jambonrose** [alexcouper/captainhook#82]
There is currently no section in the Read Me about how to contribute to the project. Most noticeably, there is nothing about how to properly test the project to ensure that pull-requests aren't introducing problems.

As far as I can tell, `nosetests` and `behave` are meant to be used.

The tests work just fine (13 tests pass on Python 3.4). The feature checks do not (on my machine):

```bash
$ behave
0 features passed, 5 failed, 0 skipped
0 scenarios passed, 5 failed, 0 skipped
5 steps passed, 5 failed, 29 skipped, 0 undefined
Took 0m0.292s
```
I am not familiar with `behave` and perhaps the error is with my environment. Without any documentation to inform me what my development environment should be, it's hard to tell.

**Comment by alexcouper** [comment]
the output you eventually want to see looks like this:
![image](https://cloud.githubusercontent.com/assets/837734/9328426/782d2c02-45a0-11e5-9647-6f3036671791.png)
![image](https://cloud.githubusercontent.com/assets/837734/9328435/889fd7ce-45a0-11e5-9739-e1b2ea21054a.png)

One thing that isn't documented is that you need to run `pip install -e .` or `python setup.py install .` so that your local captainhook is made available.

Is there any output to the behave command other than the 3 lines you show above?
Any explanation as to why they fail?
